App package renamed (#100)
The app package seems to have been renamed from "Synology Assistant.app" to "SynologyAssistant.app".

Can easily be tested by trying to install it.
`brew cask install synology-assistant`

With the old name, install fails with:
```
Error: It seems the App source '/usr/local/Caskroom/synology-assistant/6.1-15030/Synology Assistant.app' is not there.
Error: Install incomplete.
```